## Preprocessing

In [39]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [40]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'], axis = 1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [41]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [42]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [43]:
#Adding a cell to see the data type in order to code the next cell correctly
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [44]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [45]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [46]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#counts = application_df['CLASSIFICATION'].value_counts
#for i in counts:
 # if (i>1 == True):
    #print(i)

In [47]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace =['C1000','C2000','C1200','C3000','C2100']

# Replace in dataframe
#for cls in classifications_to_replace:
    #application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

#I used a different code then the provided one. Using an if statement to change the data if it's not in in the list created above
for i in application_df['CLASSIFICATION'] :
  if i not in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(i,"Other")
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [48]:
# Convert categorical data to numeric with `pd.get_dummies`
#colums to transform APPLICATION_TYPE, AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,SPECIAL_CONSIDERATIONS,INCOME_AMT
application_type_dummies = pd.get_dummies(application_df['APPLICATION_TYPE'], dtype=int)
income_amt_dummies = pd.get_dummies(application_df['INCOME_AMT'], dtype=int)
affiliation_dummies = pd.get_dummies(application_df['AFFILIATION'], dtype=int)
classification_dummies = pd.get_dummies(application_df['CLASSIFICATION'], dtype=int)
use_case_dummies = pd.get_dummies(application_df['USE_CASE'], dtype=int)
organization_dummies = pd.get_dummies(application_df['ORGANIZATION'], dtype=int)
special_considerations_dummies = pd.get_dummies(application_df['SPECIAL_CONSIDERATIONS'], dtype=int)
application_df_dummies = application_df.drop(['APPLICATION_TYPE', 'AFFILIATION','CLASSIFICATION',
                                              'USE_CASE','ORGANIZATION','SPECIAL_CONSIDERATIONS','INCOME_AMT'], axis = 1)
application_df_dummies = pd.concat([application_df_dummies,application_type_dummies,
                                   affiliation_dummies,classification_dummies,organization_dummies,
                                   special_considerations_dummies,income_amt_dummies], axis = 1 )

pd.set_option('display.max_columns', None)
application_df_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,Other,T10,T19,T3,T4,T5,T6,T7,T8,CompanySponsored,Family/Parent,Independent,National,Other,Regional,C1000,C1200,C2000,C2100,C3000,Other,Association,Co-operative,Corporation,Trust,N,Y,0,1-9999,10000-24999,100000-499999,10M-50M,1M-5M,25000-99999,50M+,5M-10M
0,1,5000,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0

In [49]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies['IS_SUCCESSFUL']
X = application_df_dummies.drop(['IS_SUCCESSFUL'], axis = 1)
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [55]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80,activation = 'tanh', input_dim = len(X.columns)))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30,activation = 'tanh'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation = 'sigmoid')) #as we want a result between 0 and 1

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 80)                3120

 dense_13 (Dense)            (None, 30)                2430

 dense_14 (Dense)            (None, 1)                 31

=================================================================
Total params: 5581 (21.80 KB)
Trainable params: 5581 (21.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [56]:
# Compile the model
nn.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [57]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs= 100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5686 - accuracy: 0.7234
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7329
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7334
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7340
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7331
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7346
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7340
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7342
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7355
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7354
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7355
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7367
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7363
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7376
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7378
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7376
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7378
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7380
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7383
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7378
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7376
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7382
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7378
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7378
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7385
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7378
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7374
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7386
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7386
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7383
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7384
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7393
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7384
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7397
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7382
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7396
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7394
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7397
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7389
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7400
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7390
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7400
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7397
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7403
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7390
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7397
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7393
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7395
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7407
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7392
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7396
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7408
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7387
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7400
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7400
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7404
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7392
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7403
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7405
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7402
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7400
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7410
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7402
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7402
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7406
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7398
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7406
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7409
Epoch 69/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5369 - accuracy: 0.7403
Epoch 70/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5368 - accuracy: 0.7397
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7402
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7402
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7404
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7398
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7405
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7404
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7395
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7405
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7408
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7403
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7403
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7399
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7397
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7406
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7404
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7401
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7411
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7401
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7407
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7405
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7406
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7406
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7403
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7409
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7409
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7408
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7402
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7412
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7410

In [58]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5657 - accuracy: 0.7205 - 493ms/epoch - 2ms/step
Loss: 0.5657095909118652, Accuracy: 0.7204664945602417

In [62]:
# Export our model to HDF5 file
nn.save('AlphabelSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(